fix nightly check

diff --git a/.github/workflows/nightly.yml b/.github/workflows/nightly.yml
--- a/.github/workflows/nightly.yml
+++ b/.github/workflows/nightly.yml
@@ -74,15 +74,19 @@ jobs:
         # Install the built wheel
         pip install ./wheelhouse/nodai*
         # Validate the Models
+        rm -rf ~/.local/shark_tank
         /bin/bash "$GITHUB_WORKSPACE/build_tools/populate_sharktank_ci.sh"
         pytest tank |
           tail -n 1 |
           tee -a pytest_results.txt
-        if !(grep -Fxq " failed" pytest_results.txt) 
-          then 
-            export SHA=$(git log -1 --format='%h')
-            gsutil -m cp -r $GITHUB_WORKSPACE/gen_shark_tank/* gs://shark_tank/$SHA
-            gsutil -m cp -r gs://shark_tank/$SHA/* gs://shark_tank/latest/
+        if !(grep -Fxq " failed" pytest_results.txt) && !(grep -Fxq " error" pytest_results.txt) 
+            then 
+              export SHA=$(git log -1 --format='%h')
+              gsutil -m cp -r $GITHUB_WORKSPACE/gen_shark_tank/* gs://shark_tank/$SHA
+              gsutil -m cp -r gs://shark_tank/$SHA/* gs://shark_tank/latest/
+        else
+            echo "Failures in tank test"
+            exit 1
         fi
         rm -rf ./wheelhouse/nodai*
 
@@ -101,6 +105,11 @@ jobs:
         pytest tank |
           tail -n 1 |
           tee -a pytest_results.txt
+        if (grep -Fxq " failed" pytest_results.txt) && (grep -Fxq " error" pytest_results.txt) 
+            echo "Failures in tank test"
+            exit 1
+        fi
+
     
     - name: Upload Release Assets
       if: ${{ matrix.backend == 'SHARK' }}
